### ISSUE TITLE
Crash client.

### ISSUE THREAD

**Issue by Pilad** [Flaxbeard/Flaxbeards-Steam-Power#232] opened 2015-03-11 14:33 UTC
[20:31:31] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception getting block type in world
	at net.minecraft.world.World.<init>(World.java:275) ~[ahb.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:97) ~[mt.class:?]
	at WorldServerOF.<init>(WorldServerOF.java:69) ~[WorldServerOF.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:65) ~[bsx.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:153) ~[bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
Caused by: java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(Unknown Source) ~[?:1.7.0_71]
	at java.lang.Integer.parseInt(Unknown Source) ~[?:1.7.0_71]
	at java.lang.Integer.parseInt(Unknown Source) ~[?:1.7.0_71]
	at flaxbeard.steamcraft.world.SteamcraftOreGen.generate(SteamcraftOreGen.java:26) ~[SteamcraftOreGen.class:?]
	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:106) ~[GameRegistry.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280) ~[ms.class:?]
	at fastcraft.a.c.a(F:84) ~[fastcraft-1.19.jar:?]
	at fastcraft.Hooks.r(F:139) ~[fastcraft-1.19.jar:?]
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1040) ~[apx.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) ~[ms.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:419) ~[ahb.class:?]
	at net.minecraft.world.World.func_147439_a(World.java:345) ~[ahb.class:?]
	at net.minecraft.world.World.func_147437_c(World.java:365) ~[ahb.class:?]
	at net.minecraft.world.World.func_147474_b(World.java:329) ~[ahb.class:?]
	at net.minecraft.world.WorldProvider.func_76566_a(WorldProvider.java:71) ~[aqo.class:?]
	at net.minecraft.world.WorldServer.func_73052_b(WorldServer.java:749) ~[mt.class:?]
	at net.minecraft.world.WorldServer.func_72963_a(WorldServer.java:715) ~[mt.class:?]
	at WorldServerOF.func_72963_a(WorldServerOF.java:80) ~[WorldServerOF.class:?]
	at net.minecraft.world.World.<init>(World.java:260) ~[ahb.class:?]
	... 6 more

**Comment by elifoster** [comment] 2015-03-11 16:03
Known issue. Duplicate of #230

**Closed by elifoster** 2015-03-11 16:03 UTC
Labels: duplicate
