### ISSUE TITLE
server crash with 28.3 on generating nether

### ISSUE THREAD

**Issue by Too-DAMN-Much** [Flaxbeard/Flaxbeards-Steam-Power#228] opened 2015-03-10 09:05 UTC
happens on generation of nether dimension and/or server start/restart (crash loop)
related blocks nether portal
mod list: http://i.imgur.com/CGN5ozp.png
crash report: http://paste.ubuntu.com/10573299/

**Comment by elifoster** [comment] 2015-03-10 16:10
Duplicate of #230.-

**Closed by elifoster** 2015-03-10 16:10 UTC
Labels: duplicate
