### ISSUE TITLE
Thaumcraft Outer Lands Not Generating

### ISSUE THREAD

**Issue by StygianDenizen** [Flaxbeard/Flaxbeards-Steam-Power#227] opened 2015-03-09 19:03 UTC
It would seem something in your mod is preventing the Outer Lands from generating properly; it's possible that this is related to the current Nether Issues but it's not clear. I *can* tell you that it seems to only be an issue with version 0.28.0 and onwards.

**Comment by elifoster** [comment] 2015-03-10 00:15
Duplicate of #224

**Closed by elifoster** 2015-03-10 00:15 UTC
Labels: duplicate
