### ISSUE TITLE
Performance hit when using Steam Heater while pressure is too low to maintain heat.

### ISSUE THREAD

**Issue by Minalien** [Flaxbeard/Flaxbeards-Steam-Power#169] opened 2014-12-24 02:54 UTC
Build: 0.27.2
Java: 8, 64-bit
Platform: Windows

When using the Steam Heater block to power a furnace, if pressure is fluctuating enough to make furnace turn on & off repeatedly, there will be a pretty heavy performance hit. (Have not yet been able to benchmark this).

Steps to replicate:
The most reliable way to replicate this seems to be using a single boiler with three Steam Heaters, each attached to a furnace with items to smelt, as in this screenshot:

![2014-12-23_18 52 37](https://cloud.githubusercontent.com/assets/303723/5545366/ff64e156-8ad4-11e4-83fd-1682c926a99b.png)

**Comment by elifoster** [comment] 2015-03-14 20:27
I reproduced the cause, but the effect was not there. Closing.

**Closed by elifoster** 2015-03-14 20:27 UTC
Labels: bug, prio:med
