### ISSUE TITLE
Update Crash

### ISSUE THREAD

**Issue by THEVOLCO** [Flaxbeard/Flaxbeards-Steam-Power#238] opened 2015-03-13 15:29 UTC
Hi,

I´ve updated the mod and now my game crashes when i try to create a new world.

Crash Report:

http://pastebin.com/AUEST1e2

**Comment by elifoster** [comment] 2015-03-13 16:01
Fixed in next version. Until then, put any integer value in the extra dimensions config options. Duplicate of #230.

**Closed by elifoster** 2015-03-13 16:01 UTC
