### ISSUE TITLE
Client crash with FastCraft [1.7.10/FSP 0.28.3]

### ISSUE THREAD

**Issue by Granik24** [Flaxbeard/Flaxbeards-Steam-Power#229] opened 2015-03-10 11:26 UTC
Hello, I have crash with FastCraft on my modpack "Yomchnology".
Modpack: http://www.technicpack.net/modpack/yomchnology
Crash here: http://pastebin.com/qzkFeZRz

**Comment by elifoster** [comment] 2015-03-10 16:10
Duplicate of #230.-

**Closed by elifoster** 2015-03-10 16:10 UTC
Labels: duplicate
