### ISSUE TITLE
game crashes when you crush lapis or redstone ores

### ISSUE THREAD

**Issue by shivachirr** [Flaxbeard/Flaxbeards-Steam-Power#204] opened 2015-02-04 14:33 UTC
i just know the moment i add lapis restone ores the game crashes i also think emerlas and diamond casue it not fully sure

**Comment by Gholuk** [comment] 2015-02-04 14:52
See Issue #200 and Issue #203 
Fix for the problem is already implemented and a new build with the rock smasher working again should be available soon.

**Comment by shivachirr** [comment] 2015-02-05 03:33
ok good to know

**Comment by satanicsanta** [comment] 2015-02-06 01:19
Duplicate of #200.

**Closed by satanicsanta** 2015-02-06 01:19 UTC
